x = int(input("Digite o valor da tabuada: "))
if x <= 10:
    print(x, "* 1 = ", x)
    y = x*2
    print(x, "* 2 = ", y)
    y= x*3
    print(x, "* 3 = ", y)
    y= x*4
    print(x, "* 4 = ", y)
    y= x*5
    print(x, "* 5 = ", y)
    y= x*6
    print(x, "* 6 = ", y)
    y= x*7
    print(x, "* 7 = ", y)
    y= x*8
    print(x, "* 8 = ", y)
    y= x*9
    print(x, "* 9 = ", y)
    y= x*10
    print(x, "* 10 = ", y)
